const DB_NAME = "vitalpeak-mobile", STORE = "state";
const catalog = window.VITALPEAK_CATALOG || { templates: [], exercises: [] };
const defaultState = { profile: { name: "" }, routines: [], activeRoutineId: null, sessions: [], weights: [], plan: {}, goals: { weeklySessions: 3, targetWeight: null, exerciseGoals: {} } };
let state = structuredClone(defaultState), route = "today", deferredPrompt, restInterval;
const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const today = () => new Date().toISOString().slice(0, 10);
const dateLabel = v => new Intl.DateTimeFormat("es-ES", { weekday:"long", day:"numeric", month:"long" }).format(new Date(`${v}T12:00:00`));
function openDB() { return new Promise((ok, no) => { const r=indexedDB.open(DB_NAME, 2); r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)}; r.onsuccess=()=>ok(r.result); r.onerror=()=>no(r.error); }); }
async function loadState() { const db=await openDB(), tx=db.transaction(STORE,"readonly"), req=tx.objectStore(STORE).get("user"); const saved=await new Promise((ok,no)=>{req.onsuccess=()=>ok(req.result);req.onerror=()=>no(req.error)}); state={...structuredClone(defaultState),...(saved||{})}; state.plan={...(state.plan||{})}; state.goals={...structuredClone(defaultState.goals),...(state.goals||{}),exerciseGoals:{...(state.goals?.exerciseGoals||{})}}; }
async function saveState() { const db=await openDB(), tx=db.transaction(STORE,"readwrite"); tx.objectStore(STORE).put(state,"user"); await new Promise((ok,no)=>{tx.oncomplete=ok;tx.onerror=()=>no(tx.error)}); }
function toast(message) { const e=document.querySelector("#toast"); e.textContent=message;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600); }
function hero(k,t,p) { return `<header class="hero"><div class="app-brand"><img src="./icon-cover.png" alt="VitalPeak"><div class="wordmark">Vital<span>Peak</span></div></div><div class="eyebrow">${k}</div><h1>${t}</h1><p>${p}</p></header>`; }
function activeRoutine() { return state.routines.find(r=>r.id===state.activeRoutineId)||state.routines[0]||null; }
function items(r=activeRoutine()) { return r?.days?.[r.activeDay||0]?.items || r?.exercises || []; }
function exercise(name) { return catalog.exercises.find(x=>x.name===name)||{name,group:"Otro",cues:["Mantén una técnica controlada."],animation:{}}; }
function mondayDate(iso=today()) { const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()-((d.getDay()+6)%7));return d; }
function isoDate(d) { return new Date(d).toISOString().slice(0,10); }
function routineById(id) { return state.routines.find(r=>r.id===id)||null; }
function planEntries(iso=today()) { const raw=state.plan?.[iso];return Array.isArray(raw)?raw:(raw?[raw]:[]); }
function plannedRoutines(iso=today()) { return planEntries(iso).map(raw=>{const [id,day]=String(raw).split("::"),r=routineById(id);return r?{...r,activeDay:Number(day||0),planKey:raw}:null}).filter(Boolean); }
function plannedRoutine(iso=today()) { const list=plannedRoutines(iso),index=Math.min(Number(state.todaySessionIndex||0),Math.max(0,list.length-1));return list[index]||null; }
function addPlanEntry(iso,value) { const entries=planEntries(iso);if(value&&!entries.includes(value))state.plan[iso]=[...entries,value]; }
function removePlanEntry(iso,value) { const entries=planEntries(iso).filter(x=>x!==value);if(entries.length)state.plan[iso]=entries;else delete state.plan[iso]; }
function sessionsThisWeek() { const s=new Date();s.setHours(0,0,0,0);s.setDate(s.getDate()-((s.getDay()+6)%7));return state.sessions.filter(x=>new Date(`${x.date}T12:00:00`)>=s); }
function currentDraft() { const r=plannedRoutine()||activeRoutine(), key=`${r?.id||"free"}::${r?.activeDay||0}`;if(!state._draft||state._draft.routineKey!==key) state._draft={routineId:r?.id,routineKey:key,date:today(),routineName:r?.name||"Entrenamiento libre",exerciseIndex:0,sets:[],restEndsAt:null}; return state._draft; }
function formatTime(s) { return `${String(Math.max(0,Math.floor(s/60))).padStart(2,"0")}:${String(Math.max(0,s%60)).padStart(2,"0")}`; }
function exerciseHistory(name) {
  const rows=[];
  for(const session of state.sessions) for(const set of session.sets||[]) if(set.exercise===name) rows.push({...set,date:session.date,routineName:session.routineName||"Entrenamiento"});
  return rows.sort((a,b)=>String(b.at||b.date).localeCompare(String(a.at||a.date)));
}
function finishOrAdvance(draft) {
  const count=items().length;
  draft.pendingChoice=false;
  if(draft.exerciseIndex>=count-1){ if(!draft.sets.length)return false; state.sessions.push({...draft}); delete state._draft; route="today"; toast("Sesión guardada"); return true; }
  draft.exerciseIndex+=1; return false;
}

function renderToday() {
  const scheduledList=plannedRoutines(), scheduled=scheduledList.length>0, r=plannedRoutine()||activeRoutine(), week=sessionsThisWeek(), latest=[...state.sessions].sort((a,b)=>b.date.localeCompare(a.date))[0];
  const sessionPicker=scheduledList.length>1?`<div class="session-picker">${scheduledList.map((x,i)=>`<button class="${i===Number(state.todaySessionIndex||0)?"selected":""}" data-action="select-today-session" data-index="${i}">${esc(x.days?.[x.activeDay]?.name||x.name)}</button>`).join("")}</div>`:"";
  return `${hero("TU ESPACIO DE ENTRENAMIENTO",`Hola${state.profile.name?`, ${esc(state.profile.name)}`:""}`,"Tu plan y tus registros están disponibles también sin conexión.")}${deferredPrompt?`<div class="install">Instala VitalPeak en tu móvil.<button class="secondary" data-action="install">Instalar</button></div>`:""}<section class="metric-grid"><div class="metric"><b>${week.length}</b><span>sesiones esta semana</span></div><div class="metric"><b>${state.sessions.length}</b><span>sesiones guardadas</span></div><div class="metric"><b>${state.weights.length?`${state.weights.at(-1).kg} kg`:"—"}</b><span>último peso</span></div></section><section class="section-head"><h2>Entrenamiento de hoy</h2><span class="pill">${dateLabel(today())}</span></section><div class="card">${r?`<span class="template-meta">${scheduled?`HOY TIENES ${scheduledList.length} ENTRENO${scheduledList.length>1?"S":""}`:"RUTINA ACTIVA"}</span><h3>${esc(r.name)}</h3><p class="muted">${items(r).length} ejercicios · ${esc(r.days?.[r.activeDay||0]?.name||"Sesión")}</p>${sessionPicker}<button class="primary wide" data-route="train">Comenzar</button>`:`<div class="empty"><b>Elige un plan para empezar.</b><br>Dispones de ${catalog.templates.length} rutinas preparadas, de 1 a 7 días.<br><br><button class="primary" data-route="routines">Ver rutinas</button></div>`}</div><button class="secondary wide" data-route="planner">Ver calendario mensual</button><section class="section-head"><h2>Última sesión</h2></section><div class="card">${latest?`<h3>${esc(latest.routineName)}</h3><p class="muted">${dateLabel(latest.date)} · ${latest.sets.length} series registradas</p><button class="secondary wide" data-route="progress">Ver progreso</button>`:`<p class="muted">Todavía no hay entrenamientos registrados.</p>`}</div>`;
}
function renderTrain() {
  const r=plannedRoutine()||activeRoutine();
  if(!r)return `${hero("ENTRENAR","Registra tu sesión","Primero selecciona una rutina preparada o crea la tuya.")}<div class="card empty"><button class="primary" data-route="routines">Ver rutinas</button></div>`;
  const draft=currentDraft(), list=items(r), index=Math.min(draft.exerciseIndex,Math.max(0,list.length-1)), ex=list[index];
  if(!ex)return `${hero("ENTRENAR",esc(r.name),"Esta sesión no tiene ejercicios.")}<button class="secondary wide" data-route="routines">Volver</button>`;
  const saved=draft.sets.filter(s=>s.exercise===ex.exercise), completed=saved.length>=Number(ex.sets||1);
  const choice=draft.pendingChoice?`<div class="decision-backdrop" role="dialog" aria-modal="true" aria-label="Series completadas"><div class="decision-card"><span class="template-meta">OBJETIVO ALCANZADO</span><h2>${Number(ex.sets||1)} series completadas</h2><p>Has alcanzado el objetivo de <b>${esc(ex.exercise)}</b>. ¿Quieres añadir otra serie o pasar al siguiente ejercicio?</p><button class="secondary wide" data-action="extra-set">Añadir otra serie</button><button class="primary wide" data-action="advance-after-target">${index===list.length-1?"Terminar sesión":"Pasar a " + esc(list[index+1].exercise)}</button></div></div>`:"";
  return `${hero("ENTRENAR",esc(r.name),"Cada serie se guarda al instante en tu teléfono.")}<div class="card"><div class="row between"><div><p class="kicker">${esc(exercise(ex.exercise).group)} · ${index+1} de ${list.length}</p><h2>${esc(ex.exercise)}</h2><p class="muted">Objetivo: ${ex.sets} × ${ex.reps} · descanso ${ex.rest_sec||90}s</p></div><button class="icon-button" data-action="exercise-detail" data-exercise="${esc(ex.exercise)}">i</button></div><div id="rest-timer" class="rest-timer">${draft.restEndsAt?"Descanso…":completed?"Objetivo de series alcanzado":"Registra la primera serie"}</div>${draft.restEndsAt?`<button class="skip-rest" data-action="skip-rest">Omitir descanso</button>`:""}<form id="set-form" class="stack"><div class="form-grid"><label class="field">Peso (kg)<input name="weight" inputmode="decimal" type="number" step="0.5" min="0" required placeholder="0"></label><label class="field">Repeticiones<input name="reps" inputmode="numeric" type="number" min="1" required placeholder="${ex.reps}"></label></div><label class="field">Notas opcionales<input name="notes" maxlength="100" placeholder="Cómo te has sentido"></label><button class="primary wide">Guardar serie ${saved.length+1}</button></form><div class="set-list">${saved.length?saved.map((s,i)=>`<span class="set">Serie ${i+1}: ${s.weight} kg × ${s.reps}</span>`).join(""):`<span class="muted small">Aún no has guardado ninguna serie.</span>`}</div></div><div class="session-nav"><button class="secondary" data-action="previous-exercise" ${index||draft.pendingChoice?"":"disabled"}>Anterior</button><button class="secondary" data-action="next-exercise" ${draft.pendingChoice?"disabled":""}>${index===list.length-1?"Finalizar":"Siguiente"}</button></div>${choice}`;
}
function cards(list) { return list.map(t=>`<button class="list-button" data-action="view-template" data-template="${esc(t.id)}"><span class="template-meta">${t.days_per_week} días · ${esc(t.level)} · ${esc(t.goal)}</span><b>${esc(t.name)}</b><span class="muted small">${esc(t.description)}</span></button>`).join(""); }
function renderRoutines() { const current=state.routines.map(r=>`<button class="list-button" data-action="activate-routine" data-id="${esc(r.id)}"><span class="template-meta">${r.id===state.activeRoutineId?"PLAN ACTIVO":"PLAN GUARDADO"}</span><b>${esc(r.name)}</b><span class="muted small">${items(r).length} ejercicios · ${esc(r.days?.[r.activeDay||0]?.name||"Sesión")}</span></button>`).join(""); const filter=state.templateDays||"all", list=catalog.templates.filter(t=>filter==="all"||String(t.days_per_week)===filter);return `${hero("RUTINAS","Planes y ejercicios","Elige una rutina completa, ajusta el día y consulta cada ejercicio.")}<section class="section-head"><h2>Tu rutina activa</h2></section><div class="stack">${current||`<div class="card empty">Aún no has seleccionado una rutina.</div>`}</div><section class="section-head"><h2>Planes preparados</h2><span class="pill">${catalog.templates.length}</span></section><div class="filter-row"><label class="field">Días por semana<select id="template-days"><option value="all">Todos</option>${[1,2,3,4,5,6,7].map(n=>`<option value="${n}" ${filter===String(n)?"selected":""}>${n} día${n>1?"s":""}</option>`).join("")}</select></label></div><div class="stack">${cards(list)}</div><section class="section-head"><h2>Catálogo de ejercicios</h2><span class="pill">${catalog.exercises.length}</span></section><div class="exercise-grid">${catalog.exercises.map(x=>`<button class="exercise-card" data-action="exercise-detail" data-exercise="${esc(x.name)}"><span>${esc(x.group)}</span><b>${esc(x.name)}</b>${x.animation?.path?`<small>Movimiento guiado</small>`:""}</button>`).join("")}</div><section class="section-head"><h2>Rutina personalizada</h2></section><div class="card"><form id="routine-form" class="stack"><label class="field">Nombre de la rutina<input name="name" required maxlength="40" placeholder="Ej. Torso + brazos"></label><label class="field">Ejercicios (uno por línea)<textarea name="exercises" required rows="5" placeholder="Press con barra en banco horizontal\nRemo con mancuerna\nElevaciones laterales"></textarea></label><button class="primary wide">Guardar rutina</button></form></div>`; }
function renderPlanner() {
  const base=new Date(`${state.plannerMonth||today().slice(0,7)+"-01"}T12:00:00`),year=base.getFullYear(),month=base.getMonth(),first=new Date(year,month,1),last=new Date(year,month+1,0),offset=(first.getDay()+6)%7;
  const program=routineById(state.plannerProgramId)||null, programs=state.routines.filter(r=>(r.days||[]).length>1);
  const allChoices=state.routines.flatMap(r=>(r.days||[]).map((d,i)=>({value:`${r.id}::${i}`,label:`${r.name} · ${d.name||`Día ${i+1}`}`})));
  const options=`<option value="">Añadir entrenamiento…</option>${allChoices.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join("")}`;
  const weekdayNames=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];
  const cells=[];for(let i=0;i<offset;i++)cells.push(`<div class="month-day blank"></div>`);for(let d=1;d<=last.getDate();d++){const date=new Date(year,month,d),iso=isoDate(date),entries=planEntries(iso),assigned=entries.map(value=>{const [id,day]=String(value).split("::"),r=routineById(id),name=r?.days?.[Number(day)]?.name||r?.name||"Entreno";return `<span class="calendar-entry">${esc(name)}<button aria-label="Quitar ${esc(name)}" data-action="remove-plan-entry" data-date="${iso}" data-value="${esc(value)}">×</button></span>`}).join("");cells.push(`<div class="month-day ${iso===today()?"today":""}"><b>${d}</b><div class="calendar-entries">${assigned}</div><select data-plan-add-date="${iso}">${options}</select></div>`)}
  const setup=program?`<section class="planner-setup"><h2>${esc(program.name)}</h2><p class="muted">Elige el día de la semana de cada sesión y se asignará a todas las fechas de este mes.</p>${program.days.map((d,i)=>`<label class="weekday-choice"><span>Día ${i+1} · ${esc(d.name)}</span><select data-program-day-index="${i}">${weekdayNames.map((name,n)=>`<option value="${n}" ${Number(state.programWeekdays?.[`${program.id}::${i}`]??i%7)===n?"selected":""}>${name}</option>`).join("")}</select></label>`).join("")}<button class="primary wide" data-action="apply-program-month">Asignar plan a todo el mes</button></section>`:"";
  return `${hero("PLANIFICAR","Calendario mensual",`${new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric"}).format(first)} · puedes añadir varios entrenos en un mismo día.`)}<div class="month-controls"><button class="secondary" data-action="previous-month">‹</button><b>${new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric"}).format(first)}</b><button class="secondary" data-action="next-month">›</button></div><label class="field">Configurar un plan de varios días<select id="planner-program"><option value="">Selecciona un plan…</option>${programs.map(r=>`<option value="${r.id}" ${r.id===program?.id?"selected":""}>${esc(r.name)}</option>`).join("")}</select></label>${setup}<div class="month-weekdays">${weekdayNames.map(x=>`<span>${x.slice(0,3)}</span>`).join("")}</div><div class="month-calendar">${cells.join("")}</div><section class="section-head"><h2>Acciones del mes</h2></section><div class="card stack"><button class="secondary wide" data-action="copy-month-next">Copiar esta configuración al mes siguiente</button><button class="secondary wide" data-action="clear-month-plan">Vaciar el mes mostrado</button></div><button class="secondary wide" data-route="today">Volver a hoy</button>`;
}
function renderGoals() {
  const goals=state.goals, sessions=sessionsThisWeek().length, latest=state.weights.at(-1)?.kg;
  const currentGoal=state.goalExercise||catalog.exercises[0]?.name||"";
  const goal=goals.exerciseGoals?.[currentGoal]||{};
  return `${hero("OBJETIVOS","Tu dirección", "Convierte el entrenamiento y el peso en metas medibles.")}<div class="metric-grid"><div class="metric"><b>${sessions}/${goals.weeklySessions}</b><span>entrenos esta semana</span></div><div class="metric"><b>${latest??"—"}</b><span>peso actual kg</span></div><div class="metric"><b>${goals.targetWeight??"—"}</b><span>peso objetivo kg</span></div></div><section class="section-head"><h2>Metas generales</h2></section><div class="card"><form id="goals-form" class="stack"><div class="form-grid"><label class="field">Entrenos por semana<select name="weeklySessions">${[1,2,3,4,5,6,7].map(n=>`<option value="${n}" ${goals.weeklySessions===n?"selected":""}>${n}</option>`).join("")}</select></label><label class="field">Peso objetivo (kg)<input name="targetWeight" inputmode="decimal" type="number" step="0.1" min="1" value="${goals.targetWeight??""}" placeholder="Opcional"></label></div><button class="primary wide">Guardar objetivos</button></form></div><section class="section-head"><h2>Meta de ejercicio</h2></section><div class="card"><form id="exercise-goal-form" class="stack"><label class="field">Ejercicio<select name="exercise">${catalog.exercises.map(x=>`<option value="${esc(x.name)}" ${x.name===currentGoal?"selected":""}>${esc(x.name)}</option>`).join("")}</select></label><div class="form-grid"><label class="field">Peso (kg)<input name="weight" inputmode="decimal" type="number" step="0.5" min="0" value="${goal.weight??""}" placeholder="Ej. 80"></label><label class="field">Repeticiones<input name="reps" inputmode="numeric" type="number" min="1" value="${goal.reps??""}" placeholder="Ej. 8"></label></div><button class="primary wide">Guardar meta del ejercicio</button></form></div><button class="secondary wide" data-route="account">Volver a cuenta</button>`;
}
function renderTemplate() { const t=catalog.templates.find(x=>x.id===state.viewTemplateId);if(!t){route="routines";return renderRoutines()}return `${hero("PLAN PREPARADO",esc(t.name),`${t.days_per_week} días · ${t.duration_min} min · ${esc(t.level)}`)}<div class="card"><p class="muted">${esc(t.description)}</p>${t.days.map((d,i)=>`<button class="day-card ${state.viewDay===i?"selected":""}" data-action="choose-day" data-day="${i}"><b>Día ${i+1} · ${esc(d.name)}</b><span>${esc(d.focus)}</span><small>${d.items.map(x=>`${x.exercise} (${x.sets}×${x.reps})`).join(" · ")}</small></button>`).join("")}</div><button class="primary wide" data-action="apply-template" data-template="${esc(t.id)}">Usar este plan</button><button class="secondary wide" data-route="routines">Volver a rutinas</button>`; }
function renderExercise() {
  const x=exercise(state.viewExercise), a=x.animation||{}, history=exerciseHistory(x.name);
  const bestWeight=history.length?Math.max(...history.map(s=>Number(s.weight)||0)):0;
  const best1rm=history.length?Math.max(...history.map(s=>(Number(s.weight)||0)*(1+(Number(s.reps)||0)/30))):0;
  const sessions=[...new Set(history.map(s=>s.date))].length;
  const recent=history.slice(0,12);
  const maxWeight=Math.max(bestWeight,1);
  return `${hero("EJERCICIO",esc(x.name),`${esc(x.group)} · técnica y progreso`)}<div class="card stack">${a.path?`<div class="movement-placeholder"><img src="./${encodeURI(a.path)}" alt="Movimiento de ${esc(x.name)}"><b>Movimiento guiado</b><span>El GIF queda disponible sin conexión después de verlo una vez.</span></div>`:""}<h2>Puntos clave</h2><ul class="cue-list">${(x.cues||[]).map(c=>`<li>${esc(c)}</li>`).join("")}</ul>${a.steps?.length?`<h3>Secuencia</h3>${a.steps.map(s=>`<div class="step"><b>${esc(s.title)}</b><span>${esc(s.tip)}</span></div>`).join("")}`:""}<section class="section-head"><h2>Tu histórico</h2><span class="pill">${history.length} series</span></section>${history.length?`<div class="metric-grid exercise-metrics"><div class="metric"><b>${sessions}</b><span>sesiones</span></div><div class="metric"><b>${bestWeight} kg</b><span>mejor carga</span></div><div class="metric"><b>${best1rm.toFixed(1)} kg</b><span>mejor 1RM</span></div></div><div class="exercise-chart">${recent.slice().reverse().map(s=>`<div class="exercise-bar" title="${esc(s.date)} · ${s.weight} kg × ${s.reps}" style="height:${Math.max(10,Number(s.weight)/maxWeight*100)}%"><span>${s.weight}</span></div>`).join("")}</div><p class="muted small">Carga de tus últimas series. Toca una barra para ver el detalle.</p><div class="history-list">${recent.map(s=>`<div><b>${esc(s.date)}</b><span>${s.weight} kg × ${s.reps} reps${s.notes?` · ${esc(s.notes)}`:""}</span></div>`).join("")}</div>`:`<p class="muted">Aún no hay series guardadas de este ejercicio.</p>`}<button class="secondary wide" data-route="routines">Volver al catálogo</button></div>`;
}
function renderProgress() { const last=state.sessions.slice(-8), max=Math.max(...last.map(s=>s.sets.reduce((n,x)=>n+Number(x.weight||0)*Number(x.reps||0),0)),1), wt=state.weights.length?`${state.weights.at(-1).kg} kg`:"Sin dato", selected=state.progressExercise||catalog.exercises[0]?.name||"",history=exerciseHistory(selected),best=Math.max(0,...history.map(x=>Number(x.weight||0))),total=Math.max(1,...history.map(x=>Number(x.weight||0)*Number(x.reps||0)));return `${hero("PROGRESO","Tu constancia cuenta","Consulta tu evolución general o cada ejercicio, incluso sin conexión.")}<div class="metric-grid"><div class="metric"><b>${state.sessions.length}</b><span>entrenamientos</span></div><div class="metric"><b>${wt}</b><span>peso actual</span></div><div class="metric"><b>${sessionsThisWeek().length}</b><span>esta semana</span></div></div><section class="section-head"><h2>Volumen reciente</h2></section><div class="card"><div class="chart">${last.length?last.map(s=>`<div class="bar" style="height:${Math.max(10,s.sets.reduce((n,x)=>n+Number(x.weight||0)*Number(x.reps||0),0)/max*100)}%"></div>`).join(""):`<p class="muted">Registra una sesión para ver tu evolución.</p>`}</div><p class="muted small">Cada barra representa el volumen de una sesión.</p></div><section class="section-head"><h2>Progreso por ejercicio</h2></section><div class="card stack"><label class="field">Elige un ejercicio<select id="progress-exercise">${catalog.exercises.map(x=>`<option value="${esc(x.name)}" ${x.name===selected?"selected":""}>${esc(x.name)} · ${esc(x.group)}</option>`).join("")}</select></label>${history.length?`<div class="metric-grid exercise-metrics"><div class="metric"><b>${history.length}</b><span>series registradas</span></div><div class="metric"><b>${best} kg</b><span>mejor peso</span></div><div class="metric"><b>${Math.max(...history.map(x=>Number(x.reps||0)))}</b><span>mejor reps</span></div></div><div class="exercise-chart">${history.slice(0,8).reverse().map(x=>`<div class="exercise-bar" title="${esc(x.date)} · ${x.weight} kg × ${x.reps}" style="height:${Math.max(10,Number(x.weight)*Number(x.reps)/total*100)}%"><span>${x.weight}×${x.reps}</span></div>`).join("")}</div><div class="history-table"><div><b>Fecha</b><b>Peso</b><b>Reps</b><b>Notas</b></div>${history.map(x=>`<div><span>${esc(x.date)}</span><span>${x.weight} kg</span><span>${x.reps}</span><span>${esc(x.notes||"—")}</span></div>`).join("")}</div>`:`<p class="muted">Todavía no has registrado series de ${esc(selected)}.</p>`}</div><section class="section-head"><h2>Registrar peso</h2></section><div class="card"><form id="weight-form" class="row"><label class="field" style="flex:1">Peso (kg)<input name="kg" inputmode="decimal" type="number" step="0.1" min="1" required placeholder="Ej. 78,5"></label><button class="primary">Guardar</button></form></div>`; }
function renderAccount() { return `${hero("CUENTA","Tus datos","VitalPeak móvil guarda la información en este dispositivo.")}<div class="card stack"><label class="field">Cómo quieres que te llamemos<input id="profile-name" maxlength="30" value="${esc(state.profile.name)}" placeholder="Tu nombre"></label><button class="primary wide" data-action="save-name">Guardar nombre</button></div><section class="section-head"><h2>Plan y objetivos</h2></section><div class="card stack"><button class="secondary wide" data-route="planner">Planificar semana</button><button class="secondary wide" data-route="goals">Ver y editar objetivos</button></div><section class="section-head"><h2>Copia de seguridad</h2></section><div class="card stack"><p class="muted">Descarga un archivo con tus rutinas, sesiones y peso. Impórtalo en otro móvil si lo necesitas.</p><button class="secondary wide" data-action="export">Exportar mis datos</button><label class="secondary wide" style="text-align:center">Importar copia<input id="import-file" type="file" accept="application/json" hidden></label></div><section class="section-head"><h2>Estado sin conexión</h2></section><div class="card"><b>${navigator.onLine?"Con conexión":"Sin conexión"}</b><p class="muted">La app y los registros locales siguen funcionando sin internet.</p></div>`; }
function updateRest() { const e=document.querySelector("#rest-timer"),d=state._draft;if(!e||!d?.restEndsAt)return;const left=Math.ceil((d.restEndsAt-Date.now())/1000);e.innerHTML=left>0?`Descanso: <b>${formatTime(left)}</b>`:`<b>Listo para la siguiente serie</b>`;if(left<=0){clearInterval(restInterval);d.restEndsAt=null;saveState();} }
function render() { clearInterval(restInterval);const view={today:renderToday,train:renderTrain,routines:renderRoutines,template:renderTemplate,exercise:renderExercise,planner:renderPlanner,goals:renderGoals,progress:renderProgress,account:renderAccount};const app=document.querySelector("#app");app.innerHTML=(view[route]||renderToday)();document.querySelectorAll("[data-route]").forEach(e=>e.classList.toggle("active",e.dataset.route===route));if(route==="train"){const d=currentDraft(),ex=items()[d.exerciseIndex],info=ex&&exercise(ex.exercise);if(info?.animation?.path)app.insertAdjacentHTML("beforeend",`<details class="train-movement"><summary>Mostrar ejercicio</summary><img src="./${encodeURI(info.animation.path)}" alt="Movimiento de ${esc(info.name)}"><p>${esc(info.animation.steps?.[0]?.tip||"Revisa el movimiento antes de continuar.")}</p></details>`);if(state._draft?.restEndsAt){updateRest();restInterval=setInterval(updateRest,1000);}} }
async function action(a, el) {
  if(a==="install"&&deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=undefined;render();return}
  if(a==="save-name"){state.profile.name=document.querySelector("#profile-name").value.trim();await saveState();toast("Nombre guardado");render();return}
  if(a==="view-template"){state.viewTemplateId=el.dataset.template;state.viewDay=0;route="template";render();return}
  if(a==="exercise-detail"){state.viewExercise=el.dataset.exercise;route="exercise";render();return}
  if(a==="choose-day"){state.viewDay=Number(el.dataset.day);render();return}
  if(a==="apply-template"){const t=catalog.templates.find(x=>x.id===el.dataset.template);if(!t)return;const id=`template-${t.id}-${Date.now()}`;state.routines.unshift({id,name:t.name,days:structuredClone(t.days),activeDay:state.viewDay||0,source:"template"});state.activeRoutineId=id;state.plannerProgramId=id;await saveState();route="planner";toast("Elige los días para cada sesión del plan");render();return}
  if(a==="activate-routine"){state.activeRoutineId=el.dataset.id;await saveState();toast("Rutina activa");render();return}
  if(a==="select-today-session"){state.todaySessionIndex=Number(el.dataset.index)||0;delete state._draft;await saveState();render();return}
  if(a==="previous-month"||a==="next-month"){const base=new Date(`${state.plannerMonth||today().slice(0,7)+"-01"}T12:00:00`);base.setMonth(base.getMonth()+(a==="next-month"?1:-1));state.plannerMonth=isoDate(new Date(base.getFullYear(),base.getMonth(),1));render();return}
  if(a==="apply-program-month"){const program=routineById(state.plannerProgramId);if(!program)return toast("Selecciona un plan");const base=new Date(`${state.plannerMonth||today().slice(0,7)+"-01"}T12:00:00`),days=state.programWeekdays||{};let added=0;for(let d=1;d<=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();d++){const date=new Date(base.getFullYear(),base.getMonth(),d);program.days.forEach((_,i)=>{if(date.getDay()===(Number(days[`${program.id}::${i}`]??i%7)+1)%7){addPlanEntry(isoDate(date),`${program.id}::${i}`);added++}})}await saveState();toast(`${added} sesiones asignadas este mes`);render();return}
  if(a==="remove-plan-entry"){removePlanEntry(el.dataset.date,el.dataset.value);await saveState();toast("Entrenamiento quitado");render();return}
  if(a==="copy-month-next"){const base=new Date(`${state.plannerMonth||today().slice(0,7)+"-01"}T12:00:00`),year=base.getFullYear(),month=base.getMonth(),pattern={};for(let d=1;d<=new Date(year,month+1,0).getDate();d++){const src=new Date(year,month,d),entries=planEntries(isoDate(src));if(entries.length&&!pattern[src.getDay()])pattern[src.getDay()]=entries}const next=new Date(year,month+1,1),last=new Date(next.getFullYear(),next.getMonth()+1,0);let copied=0;for(let d=1;d<=last.getDate();d++){const dst=new Date(next.getFullYear(),next.getMonth(),d),entries=pattern[dst.getDay()]||[];entries.forEach(value=>{addPlanEntry(isoDate(dst),value);copied++})}await saveState();toast(copied?`${copied} sesiones copiadas al mes siguiente`:"No hay asignaciones que copiar");render();return}
  if(a==="clear-month-plan"){const base=new Date(`${state.plannerMonth||today().slice(0,7)+"-01"}T12:00:00`),year=base.getFullYear(),month=base.getMonth();Object.keys(state.plan).forEach(iso=>{const d=new Date(`${iso}T12:00:00`);if(d.getFullYear()===year&&d.getMonth()===month)delete state.plan[iso]});await saveState();toast("Mes vaciado");render();return}
  if(a==="skip-rest"){currentDraft().restEndsAt=null;await saveState();toast("Descanso omitido");render();return}
  if(a==="extra-set"){currentDraft().pendingChoice=false;await saveState();toast("Añade una serie extra cuando quieras");render();return}
  if(a==="advance-after-target"){finishOrAdvance(currentDraft());await saveState();render();return}
  if(a==="previous-exercise"||a==="next-exercise"){const d=currentDraft();if(a==="previous-exercise")d.exerciseIndex=Math.max(0,d.exerciseIndex-1);else {if(!d.sets.length)return toast("Guarda al menos una serie antes de terminar");finishOrAdvance(d)}await saveState();render();return}
  if(a==="export"){const b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),l=document.createElement("a");l.href=URL.createObjectURL(b);l.download=`vitalpeak-${today()}.json`;l.click();URL.revokeObjectURL(l.href);}
}
document.addEventListener("click",async e=>{const r=e.target.closest("[data-route]");if(r){route=r.dataset.route;render();return}const a=e.target.closest("[data-action]");if(a)await action(a.dataset.action,a)});
document.addEventListener("submit",async e=>{e.preventDefault();const f=e.target,d=new FormData(f);if(f.id==="set-form"){const draft=currentDraft(),ex=items()[draft.exerciseIndex];draft.sets.push({exercise:ex.exercise,weight:Number(d.get("weight")),reps:Number(d.get("reps")),notes:d.get("notes")||"",at:new Date().toISOString()});draft.restEndsAt=Date.now()+Number(ex.rest_sec||90)*1000;const count=draft.sets.filter(s=>s.exercise===ex.exercise).length;if(count>=Number(ex.sets||1))draft.pendingChoice=true;await saveState();toast(count>=Number(ex.sets||1)?"Series objetivo alcanzadas":"Serie guardada y descanso iniciado");render();return}if(f.id==="routine-form"){const id=`custom-${Date.now()}`,its=String(d.get("exercises")).split("\n").map(x=>x.trim()).filter(Boolean).map(exercise=>({exercise,sets:3,reps:10,rest_sec:90,weight:0}));state.routines.unshift({id,name:String(d.get("name")).trim(),days:[{name:"Sesión",focus:"Rutina personalizada",items:its}],activeDay:0,source:"custom"});state.activeRoutineId=id;await saveState();toast("Rutina creada");render();return}if(f.id==="goals-form"){state.goals.weeklySessions=Number(d.get("weeklySessions"))||3;const w=String(d.get("targetWeight")||"").trim();state.goals.targetWeight=w?Number(w):null;await saveState();toast("Objetivos guardados");render();return}if(f.id==="exercise-goal-form"){const name=String(d.get("exercise"));const w=String(d.get("weight")||"").trim(), reps=String(d.get("reps")||"").trim();if(!w&&!reps)delete state.goals.exerciseGoals[name];else state.goals.exerciseGoals[name]={weight:w?Number(w):null,reps:reps?Number(reps):null};state.goalExercise=name;await saveState();toast("Meta del ejercicio guardada");render();return}if(f.id==="weight-form"){state.weights.push({date:today(),kg:Number(d.get("kg"))});await saveState();toast("Peso guardado");render();return}});
document.addEventListener("change",async e=>{if(e.target.id==="template-days"){state.templateDays=e.target.value;render();return}if(e.target.id==="planner-program"){state.plannerProgramId=e.target.value||null;render();return}if(e.target.matches("[data-program-day-index]")){const program=routineById(state.plannerProgramId);state.programWeekdays={...(state.programWeekdays||{}),[`${program.id}::${e.target.dataset.programDayIndex}`]:Number(e.target.value)};render();return}if(e.target.matches("[data-plan-add-date]")){if(e.target.value){addPlanEntry(e.target.dataset.planAddDate,e.target.value);await saveState();toast("Entrenamiento añadido")}render();return}if(e.target.id==="progress-exercise"){state.progressExercise=e.target.value;render();return}if(e.target.id!=="import-file")return;const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());if(!imported||!Array.isArray(imported.sessions)||!Array.isArray(imported.routines))throw Error();state={...structuredClone(defaultState),...imported};delete state._draft;await saveState();toast("Copia importada correctamente");render()}catch{toast("Ese archivo no es una copia válida de VitalPeak")}});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;render()});window.addEventListener("online",render);window.addEventListener("offline",render);if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));await loadState();render();
