const DB_NAME = "vitalpeak-mobile", STORE = "state";
const catalog = window.VITALPEAK_CATALOG || { templates: [], exercises: [] };
const defaultState = { profile: { name: "" }, routines: [], activeRoutineId: null, sessions: [], weights: [] };
let state = structuredClone(defaultState), route = "today", deferredPrompt, restInterval;
const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const today = () => new Date().toISOString().slice(0, 10);
const dateLabel = v => new Intl.DateTimeFormat("es-ES", { weekday:"long", day:"numeric", month:"long" }).format(new Date(`${v}T12:00:00`));
function openDB() { return new Promise((ok, no) => { const r=indexedDB.open(DB_NAME, 2); r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)}; r.onsuccess=()=>ok(r.result); r.onerror=()=>no(r.error); }); }
async function loadState() { const db=await openDB(), tx=db.transaction(STORE,"readonly"), req=tx.objectStore(STORE).get("user"); const saved=await new Promise((ok,no)=>{req.onsuccess=()=>ok(req.result);req.onerror=()=>no(req.error)}); state={...structuredClone(defaultState),...(saved||{})}; }
async function saveState() { const db=await openDB(), tx=db.transaction(STORE,"readwrite"); tx.objectStore(STORE).put(state,"user"); await new Promise((ok,no)=>{tx.oncomplete=ok;tx.onerror=()=>no(tx.error)}); }
function toast(message) { const e=document.querySelector("#toast"); e.textContent=message;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600); }
function hero(k,t,p) { return `<header class="hero"><div class="app-brand"><img src="./icon-cover.png" alt="VitalPeak"><div class="wordmark">Vital<span>Peak</span></div></div><div class="eyebrow">${k}</div><h1>${t}</h1><p>${p}</p></header>`; }
function activeRoutine() { return state.routines.find(r=>r.id===state.activeRoutineId)||state.routines[0]||null; }
function items(r=activeRoutine()) { return r?.days?.[r.activeDay||0]?.items || r?.exercises || []; }
function exercise(name) { return catalog.exercises.find(x=>x.name===name)||{name,group:"Otro",cues:["Mantén una técnica controlada."],animation:{}}; }
function sessionsThisWeek() { const s=new Date();s.setHours(0,0,0,0);s.setDate(s.getDate()-((s.getDay()+6)%7));return state.sessions.filter(x=>new Date(`${x.date}T12:00:00`)>=s); }
function currentDraft() { const r=activeRoutine(); if(!state._draft||state._draft.routineId!==r?.id) state._draft={routineId:r?.id,date:today(),routineName:r?.name||"Entrenamiento libre",exerciseIndex:0,sets:[],restEndsAt:null}; return state._draft; }
function formatTime(s) { return `${String(Math.max(0,Math.floor(s/60))).padStart(2,"0")}:${String(Math.max(0,s%60)).padStart(2,"0")}`; }
function exerciseHistory(name) {
  const rows=[];
  for(const session of state.sessions) for(const set of session.sets||[]) if(set.exercise===name) rows.push({...set,date:session.date,routineName:session.routineName||"Entrenamiento"});
  return rows.sort((a,b)=>String(b.at||b.date).localeCompare(String(a.at||a.date)));
}
function finishOrAdvance(draft) {
  const count=items().length;
  draft.pendingChoice=false;
  if(draft.exerciseIndex>=count-1){ if(!draft.sets.length)return false; state.sessions.push({...draft}); delete state._draft; route="today"; toast("Sesión guardada"); return true; }
  draft.exerciseIndex+=1; return false;
}

function renderToday() { const r=activeRoutine(), week=sessionsThisWeek(), latest=[...state.sessions].sort((a,b)=>b.date.localeCompare(a.date))[0]; return `${hero("TU ESPACIO DE ENTRENAMIENTO",`Hola${state.profile.name?`, ${esc(state.profile.name)}`:""}`,"Tu plan y tus registros están disponibles también sin conexión.")}${deferredPrompt?`<div class="install">Instala VitalPeak en tu móvil.<button class="secondary" data-action="install">Instalar</button></div>`:""}<section class="metric-grid"><div class="metric"><b>${week.length}</b><span>sesiones esta semana</span></div><div class="metric"><b>${state.sessions.length}</b><span>sesiones guardadas</span></div><div class="metric"><b>${state.weights.length?`${state.weights.at(-1).kg} kg`:"—"}</b><span>último peso</span></div></section><section class="section-head"><h2>Entrenamiento de hoy</h2><span class="pill">${dateLabel(today())}</span></section><div class="card">${r?`<h3>${esc(r.name)}</h3><p class="muted">${items(r).length} ejercicios · ${esc(r.days?.[r.activeDay||0]?.name||"Sesión")}</p><button class="primary wide" data-route="train">Empezar entrenamiento</button>`:`<div class="empty"><b>Elige un plan para empezar.</b><br>Dispones de ${catalog.templates.length} rutinas preparadas, de 1 a 7 días.<br><br><button class="primary" data-route="routines">Ver rutinas</button></div>`}</div><section class="section-head"><h2>Última sesión</h2></section><div class="card">${latest?`<h3>${esc(latest.routineName)}</h3><p class="muted">${dateLabel(latest.date)} · ${latest.sets.length} series registradas</p><button class="secondary wide" data-route="progress">Ver progreso</button>`:`<p class="muted">Todavía no hay entrenamientos registrados.</p>`}</div>`; }
function renderTrain() {
  const r=activeRoutine();
  if(!r)return `${hero("ENTRENAR","Registra tu sesión","Primero selecciona una rutina preparada o crea la tuya.")}<div class="card empty"><button class="primary" data-route="routines">Ver rutinas</button></div>`;
  const draft=currentDraft(), list=items(r), index=Math.min(draft.exerciseIndex,Math.max(0,list.length-1)), ex=list[index];
  if(!ex)return `${hero("ENTRENAR",esc(r.name),"Esta sesión no tiene ejercicios.")}<button class="secondary wide" data-route="routines">Volver</button>`;
  const saved=draft.sets.filter(s=>s.exercise===ex.exercise), completed=saved.length>=Number(ex.sets||1);
  const choice=draft.pendingChoice?`<div class="decision-backdrop" role="dialog" aria-modal="true" aria-label="Series completadas"><div class="decision-card"><span class="template-meta">OBJETIVO ALCANZADO</span><h2>${Number(ex.sets||1)} series completadas</h2><p>Has alcanzado el objetivo de <b>${esc(ex.exercise)}</b>. ¿Quieres añadir otra serie o pasar al siguiente ejercicio?</p><button class="secondary wide" data-action="extra-set">Añadir otra serie</button><button class="primary wide" data-action="advance-after-target">${index===list.length-1?"Terminar sesión":"Pasar a " + esc(list[index+1].exercise)}</button></div></div>`:"";
  return `${hero("ENTRENAR",esc(r.name),"Cada serie se guarda al instante en tu teléfono.")}<div class="card"><div class="row between"><div><p class="kicker">${esc(exercise(ex.exercise).group)} · ${index+1} de ${list.length}</p><h2>${esc(ex.exercise)}</h2><p class="muted">Objetivo: ${ex.sets} × ${ex.reps} · descanso ${ex.rest_sec||90}s</p></div><button class="icon-button" data-action="exercise-detail" data-exercise="${esc(ex.exercise)}">i</button></div><div id="rest-timer" class="rest-timer">${draft.restEndsAt?"Descanso…":completed?"Objetivo de series alcanzado":"Registra la primera serie"}</div>${draft.restEndsAt?`<button class="skip-rest" data-action="skip-rest">Omitir descanso</button>`:""}<form id="set-form" class="stack"><div class="form-grid"><label class="field">Peso (kg)<input name="weight" inputmode="decimal" type="number" step="0.5" min="0" required placeholder="0"></label><label class="field">Repeticiones<input name="reps" inputmode="numeric" type="number" min="1" required placeholder="${ex.reps}"></label></div><label class="field">Notas opcionales<input name="notes" maxlength="100" placeholder="Cómo te has sentido"></label><button class="primary wide">Guardar serie ${saved.length+1}</button></form><div class="set-list">${saved.length?saved.map((s,i)=>`<span class="set">Serie ${i+1}: ${s.weight} kg × ${s.reps}</span>`).join(""):`<span class="muted small">Aún no has guardado ninguna serie.</span>`}</div></div><div class="session-nav"><button class="secondary" data-action="previous-exercise" ${index||draft.pendingChoice?"":"disabled"}>Anterior</button><button class="secondary" data-action="next-exercise" ${draft.pendingChoice?"disabled":""}>${index===list.length-1?"Finalizar":"Siguiente"}</button></div>${choice}`;
}
function cards(list) { return list.map(t=>`<button class="list-button" data-action="view-template" data-template="${esc(t.id)}"><span class="template-meta">${t.days_per_week} días · ${esc(t.level)} · ${esc(t.goal)}</span><b>${esc(t.name)}</b><span class="muted small">${esc(t.description)}</span></button>`).join(""); }
function renderRoutines() { const current=state.routines.map(r=>`<button class="list-button" data-action="activate-routine" data-id="${esc(r.id)}"><span class="template-meta">${r.id===state.activeRoutineId?"PLAN ACTIVO":"PLAN GUARDADO"}</span><b>${esc(r.name)}</b><span class="muted small">${items(r).length} ejercicios · ${esc(r.days?.[r.activeDay||0]?.name||"Sesión")}</span></button>`).join(""); const filter=state.templateDays||"all", list=catalog.templates.filter(t=>filter==="all"||String(t.days_per_week)===filter);return `${hero("RUTINAS","Planes y ejercicios","Elige una rutina completa, ajusta el día y consulta cada ejercicio.")}<section class="section-head"><h2>Tu rutina activa</h2></section><div class="stack">${current||`<div class="card empty">Aún no has seleccionado una rutina.</div>`}</div><section class="section-head"><h2>Planes preparados</h2><span class="pill">${catalog.templates.length}</span></section><div class="filter-row"><label class="field">Días por semana<select id="template-days"><option value="all">Todos</option>${[1,2,3,4,5,6,7].map(n=>`<option value="${n}" ${filter===String(n)?"selected":""}>${n} día${n>1?"s":""}</option>`).join("")}</select></label></div><div class="stack">${cards(list)}</div><section class="section-head"><h2>Catálogo de ejercicios</h2><span class="pill">${catalog.exercises.length}</span></section><div class="exercise-grid">${catalog.exercises.map(x=>`<button class="exercise-card" data-action="exercise-detail" data-exercise="${esc(x.name)}"><span>${esc(x.group)}</span><b>${esc(x.name)}</b>${x.animation?.path?`<small>Movimiento guiado</small>`:""}</button>`).join("")}</div><section class="section-head"><h2>Rutina personalizada</h2></section><div class="card"><form id="routine-form" class="stack"><label class="field">Nombre de la rutina<input name="name" required maxlength="40" placeholder="Ej. Torso + brazos"></label><label class="field">Ejercicios (uno por línea)<textarea name="exercises" required rows="5" placeholder="Press con barra en banco horizontal\nRemo con mancuerna\nElevaciones laterales"></textarea></label><button class="primary wide">Guardar rutina</button></form></div>`; }
function renderTemplate() { const t=catalog.templates.find(x=>x.id===state.viewTemplateId);if(!t){route="routines";return renderRoutines()}return `${hero("PLAN PREPARADO",esc(t.name),`${t.days_per_week} días · ${t.duration_min} min · ${esc(t.level)}`)}<div class="card"><p class="muted">${esc(t.description)}</p>${t.days.map((d,i)=>`<button class="day-card ${state.viewDay===i?"selected":""}" data-action="choose-day" data-day="${i}"><b>Día ${i+1} · ${esc(d.name)}</b><span>${esc(d.focus)}</span><small>${d.items.map(x=>`${x.exercise} (${x.sets}×${x.reps})`).join(" · ")}</small></button>`).join("")}</div><button class="primary wide" data-action="apply-template" data-template="${esc(t.id)}">Usar este plan</button><button class="secondary wide" data-route="routines">Volver a rutinas</button>`; }
function renderExercise() {
  const x=exercise(state.viewExercise), a=x.animation||{}, history=exerciseHistory(x.name);
  const bestWeight=history.length?Math.max(...history.map(s=>Number(s.weight)||0)):0;
  const best1rm=history.length?Math.max(...history.map(s=>(Number(s.weight)||0)*(1+(Number(s.reps)||0)/30))):0;
  const sessions=[...new Set(history.map(s=>s.date))].length;
  const recent=history.slice(0,12);
  const maxWeight=Math.max(bestWeight,1);
  return `${hero("EJERCICIO",esc(x.name),`${esc(x.group)} · técnica y progreso`)}<div class="card stack">${a.path?`<div class="movement-placeholder"><img src="./${encodeURI(a.path)}" alt="Movimiento de ${esc(x.name)}"><b>Movimiento guiado</b><span>El GIF queda disponible sin conexión después de verlo una vez.</span></div>`:""}<h2>Puntos clave</h2><ul class="cue-list">${(x.cues||[]).map(c=>`<li>${esc(c)}</li>`).join("")}</ul>${a.steps?.length?`<h3>Secuencia</h3>${a.steps.map(s=>`<div class="step"><b>${esc(s.title)}</b><span>${esc(s.tip)}</span></div>`).join("")}`:""}<section class="section-head"><h2>Tu histórico</h2><span class="pill">${history.length} series</span></section>${history.length?`<div class="metric-grid exercise-metrics"><div class="metric"><b>${sessions}</b><span>sesiones</span></div><div class="metric"><b>${bestWeight} kg</b><span>mejor carga</span></div><div class="metric"><b>${best1rm.toFixed(1)} kg</b><span>mejor 1RM</span></div></div><div class="exercise-chart">${recent.slice().reverse().map(s=>`<div class="exercise-bar" title="${esc(s.date)} · ${s.weight} kg × ${s.reps}" style="height:${Math.max(10,Number(s.weight)/maxWeight*100)}%"><span>${s.weight}</span></div>`).join("")}</div><p class="muted small">Carga de tus últimas series. Toca una barra para ver el detalle.</p><div class="history-list">${recent.map(s=>`<div><b>${esc(s.date)}</b><span>${s.weight} kg × ${s.reps} reps${s.notes?` · ${esc(s.notes)}`:""}</span></div>`).join("")}</div>`:`<p class="muted">Aún no hay series guardadas de este ejercicio.</p>`}<button class="secondary wide" data-route="routines">Volver al catálogo</button></div>`;
}
function renderProgress() { const last=state.sessions.slice(-8), max=Math.max(...last.map(s=>s.sets.reduce((n,x)=>n+Number(x.weight||0)*Number(x.reps||0),0)),1), wt=state.weights.length?`${state.weights.at(-1).kg} kg`:"Sin dato";return `${hero("PROGRESO","Tu constancia cuenta","Los datos de esta pantalla permanecen en tu teléfono.")}<div class="metric-grid"><div class="metric"><b>${state.sessions.length}</b><span>entrenamientos</span></div><div class="metric"><b>${wt}</b><span>peso actual</span></div><div class="metric"><b>${sessionsThisWeek().length}</b><span>esta semana</span></div></div><section class="section-head"><h2>Volumen reciente</h2></section><div class="card"><div class="chart">${last.length?last.map(s=>`<div class="bar" style="height:${Math.max(10,s.sets.reduce((n,x)=>n+Number(x.weight||0)*Number(x.reps||0),0)/max*100)}%"></div>`).join(""):`<p class="muted">Registra una sesión para ver tu evolución.</p>`}</div><p class="muted small">Cada barra representa el volumen de una sesión.</p></div><section class="section-head"><h2>Registrar peso</h2></section><div class="card"><form id="weight-form" class="row"><label class="field" style="flex:1">Peso (kg)<input name="kg" inputmode="decimal" type="number" step="0.1" min="1" required placeholder="Ej. 78,5"></label><button class="primary">Guardar</button></form></div>`; }
function renderAccount() { return `${hero("CUENTA","Tus datos","VitalPeak móvil guarda la información en este dispositivo.")}<div class="card stack"><label class="field">Cómo quieres que te llamemos<input id="profile-name" maxlength="30" value="${esc(state.profile.name)}" placeholder="Tu nombre"></label><button class="primary wide" data-action="save-name">Guardar nombre</button></div><section class="section-head"><h2>Copia de seguridad</h2></section><div class="card stack"><p class="muted">Descarga un archivo con tus rutinas, sesiones y peso. Impórtalo en otro móvil si lo necesitas.</p><button class="secondary wide" data-action="export">Exportar mis datos</button><label class="secondary wide" style="text-align:center">Importar copia<input id="import-file" type="file" accept="application/json" hidden></label></div><section class="section-head"><h2>Estado sin conexión</h2></section><div class="card"><b>${navigator.onLine?"Con conexión":"Sin conexión"}</b><p class="muted">La app y los registros locales siguen funcionando sin internet.</p></div>`; }
function updateRest() { const e=document.querySelector("#rest-timer"),d=state._draft;if(!e||!d?.restEndsAt)return;const left=Math.ceil((d.restEndsAt-Date.now())/1000);e.innerHTML=left>0?`Descanso: <b>${formatTime(left)}</b>`:`<b>Listo para la siguiente serie</b>`;if(left<=0){clearInterval(restInterval);d.restEndsAt=null;saveState();} }
function render() { clearInterval(restInterval);const view={today:renderToday,train:renderTrain,routines:renderRoutines,template:renderTemplate,exercise:renderExercise,progress:renderProgress,account:renderAccount};document.querySelector("#app").innerHTML=(view[route]||renderToday)();document.querySelectorAll("[data-route]").forEach(e=>e.classList.toggle("active",e.dataset.route===route));if(route==="train"&&state._draft?.restEndsAt){updateRest();restInterval=setInterval(updateRest,1000);} }
async function action(a, el) {
  if(a==="install"&&deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=undefined;render();return}
  if(a==="save-name"){state.profile.name=document.querySelector("#profile-name").value.trim();await saveState();toast("Nombre guardado");render();return}
  if(a==="view-template"){state.viewTemplateId=el.dataset.template;state.viewDay=0;route="template";render();return}
  if(a==="exercise-detail"){state.viewExercise=el.dataset.exercise;route="exercise";render();return}
  if(a==="choose-day"){state.viewDay=Number(el.dataset.day);render();return}
  if(a==="apply-template"){const t=catalog.templates.find(x=>x.id===el.dataset.template);if(!t)return;const id=`template-${t.id}-${Date.now()}`;state.routines.unshift({id,name:t.name,days:structuredClone(t.days),activeDay:state.viewDay||0,source:"template"});state.activeRoutineId=id;await saveState();route="today";toast("Plan asignado");render();return}
  if(a==="activate-routine"){state.activeRoutineId=el.dataset.id;await saveState();toast("Rutina activa");render();return}
  if(a==="skip-rest"){currentDraft().restEndsAt=null;await saveState();toast("Descanso omitido");render();return}
  if(a==="extra-set"){currentDraft().pendingChoice=false;await saveState();toast("Añade una serie extra cuando quieras");render();return}
  if(a==="advance-after-target"){finishOrAdvance(currentDraft());await saveState();render();return}
  if(a==="previous-exercise"||a==="next-exercise"){const d=currentDraft();if(a==="previous-exercise")d.exerciseIndex=Math.max(0,d.exerciseIndex-1);else {if(!d.sets.length)return toast("Guarda al menos una serie antes de terminar");finishOrAdvance(d)}await saveState();render();return}
  if(a==="export"){const b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),l=document.createElement("a");l.href=URL.createObjectURL(b);l.download=`vitalpeak-${today()}.json`;l.click();URL.revokeObjectURL(l.href);}
}
document.addEventListener("click",async e=>{const r=e.target.closest("[data-route]");if(r){route=r.dataset.route;render();return}const a=e.target.closest("[data-action]");if(a)await action(a.dataset.action,a)});
document.addEventListener("submit",async e=>{e.preventDefault();const f=e.target,d=new FormData(f);if(f.id==="set-form"){const draft=currentDraft(),ex=items()[draft.exerciseIndex];draft.sets.push({exercise:ex.exercise,weight:Number(d.get("weight")),reps:Number(d.get("reps")),notes:d.get("notes")||"",at:new Date().toISOString()});draft.restEndsAt=Date.now()+Number(ex.rest_sec||90)*1000;const count=draft.sets.filter(s=>s.exercise===ex.exercise).length;if(count>=Number(ex.sets||1))draft.pendingChoice=true;await saveState();toast(count>=Number(ex.sets||1)?"Series objetivo alcanzadas":"Serie guardada y descanso iniciado");render()}if(f.id==="routine-form"){const id=`custom-${Date.now()}`,its=String(d.get("exercises")).split("\n").map(x=>x.trim()).filter(Boolean).map(exercise=>({exercise,sets:3,reps:10,rest_sec:90,weight:0}));state.routines.unshift({id,name:String(d.get("name")).trim(),days:[{name:"Sesión",focus:"Rutina personalizada",items:its}],activeDay:0,source:"custom"});state.activeRoutineId=id;await saveState();toast("Rutina creada");render()}if(f.id==="weight-form"){state.weights.push({date:today(),kg:Number(d.get("kg"))});await saveState();toast("Peso guardado");render()}});
document.addEventListener("change",async e=>{if(e.target.id==="template-days"){state.templateDays=e.target.value;render();return}if(e.target.id!=="import-file")return;const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());if(!imported||!Array.isArray(imported.sessions)||!Array.isArray(imported.routines))throw Error();state={...structuredClone(defaultState),...imported};delete state._draft;await saveState();toast("Copia importada correctamente");render()}catch{toast("Ese archivo no es una copia válida de VitalPeak")}});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;render()});window.addEventListener("online",render);window.addEventListener("offline",render);if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));await loadState();render();
